SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_NAME, SYSDATE AS CURRENT_DATE FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, SYSDATE AS CURRENT_DATE FROM EMPLOYEES E WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES)
ORDER BY SALARY DESC
FETCH FIRST 10 ROWS ONLY;

SELECT D.DEPARTMENT_NAME, COUNT(E.EMPLOYEE_ID) AS NUM_EMPLOYEES, SYSDATE AS CURRENT_DATE FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME;

SELECT E.FIRST_NAME ||' '|| E.LAST_NAME AS EMPLOYEE_NAME, E.SALARY, D.DEPARTMENT_NAME, L.CITY FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
LEFT JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID;

CREATE OR REPLACE TRIGGER TRG_SALARY_CHANGE
BEFORE UPDATE OF SALARY ON EMPLOYEES FOR EACH ROW
WHEN (NEW.SALARY <> OLD.SALARY)
BEGIN
	INSERT INTO JOB_HISTORY (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID)
	VALUES (:OLD.EMPLOYEE_ID, SYSDATE, SYSDATE, :OLD.JOB_ID, :OLD.DEPARTMENT_ID);
END;

CREATE MATERIALIZED VIEW MV_AVGSALARY_DEPT
	BUILD IMMEDIATE
	REFRESH START WITH SYSDATE
	NEXT SYSDATE +1
	AS SELECT DEPARTMENT_ID, AVG(SALARY) AS AVG_SALARY
	FROM EMPLOYEES
	GROUP BY DEPARTMENT_ID;

CREATE OR REPLACE PROCEDURE UPDATE_SALARY_DEPT (P_DEPARTMENT_ID IN EMPLOYEES.DEPARTMENT_ID%TYPE, P_PERCENTAGE IN NUMBER)
AS
BEGIN
	UPDATE EMPLOYEES SET SALARY = SALARY * (1 + P_PERCENTAGE / 100)
	WHERE DEPARTMENT_ID = P_DEPARTMENT_ID;
	COMMIT;
END;
/

CREATE OR REPLACE FUNCTION CALCULATE_BONUS(
	F_EMPLOYEE_ID NUMBER
)	RETURN NUMBER IS
		V_SALARY_NUMBER;
		V_HIRE_DATE DATE;
		V_YEARS NUMBER;
		V_BONUS NUMBER;
BEGIN
	SELECT SALARY, HIRE_DATE INTO V_SALARY, V_HIRE_DATE FROM EMPLOYEES WHERE EMPLOYEE_ID = F_EMPLOYEE_ID;
	V_YEARS := EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM V_HIRE_DATE);
	V_BONUS := V_SALARY * (V_YEARS * 0.05);
	RETURN V_BONUS;
END CALCULATE_BONUS;
/

CREATE OR REPLACE PROCEDURE INCREASE_SALARY (P_DEPARTMENT_ID NUMBER) IS
	CURSOR INC_CURSOR IS
	SELECT EMPLOYEE_ID, SALARY, HIRE_DATE FROM EMPLOYEES WHERE DEPARTMENT_ID = P_DEPARTMENT_ID;
	V_EMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE;
	V_SALARY EMPLOYEES.SALARY%TYPE;
	V_HIRE_DATE EMPLOYEES.HIRE_DATE%TYPE;
	V_YEARS NUMBER;
BEGIN
	OPEN INC_CURSOR;
	LOOP
		FETCH INC_CURSOR INTO V_EMPLOYEE_ID, V_SALARY, V_HIRE_DATE;
		EXIT WHEN INC_CURSOR%NOTFOUND;

		V_YEARS := EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM V_HIRE_DATE);

		IF V_YEARS > 2 THEN
			UPDATE EMPLOYEES
			SET SALARY = SALARY * 1.10 WHERE EMPLOYEE_ID = V_EMPLOYEE_ID;
		END IF;
	END LOOP;
	CLOSE INC_CURSOR;

	COMMIT;
END INCREASE_SALARY;
/

CREATE OR REPLACE PROCEDURE DEPT_EMP_STATS(
	P_DEPARTMENT_ID IN EMPLOYEES.DEPARTMENT_ID%TYPE,
	P_EMPLOYEES_COUNT OUT NUMBER,
	P_TOTAL_SALARY OUT NUMBER
) AS
BEGIN
	SELECT COUNT(*), NVL(SUM(SALARY), 0)
	INTO P_EMPLOYEES_COUNT, P_TOTAL_SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = P_DEPARTMENT_ID;
END;
/
DECLARE
	V_EMPLOYEES_COUNT NUMBER;
	V_TOTAL_SALARY NUMBER;
BEGIN
	DEPT_EMP_STATS(50, V_EMPLOYEES_COUNT, V_TOTAL_SALARY);

	DBMS_OUTPUT.PUT_LINE('Employees: ' || V_EMPLOYEES_COUNT);
	DBMS_OUTPUT.PUT_LINE('Total salary: ' || V_TOTAL_SALARY);
END;
/