CREATE USER DBA_2031 IDENTIFIED BY oracle; GRANT DBA TO DBA_2031;
CREATE TABLESPACE rhumano DATAFILE '/mnt/disco_100mb/rhumano.dbf' SIZE 10M AUTOEXTEND OFF;
CREATE TABLESPACE contable DATAFILE '/mnt/disco_100mb/contable.dbf' SIZE 15M AUTOEXTEND OFF;

SELECT object_name, object_type, owner, SYSDATE AS fecha_consulta FROM dba_objects WHERE owner = 'HR';
SELECT owner, segment_name AS table_name, ROUND(SUM(bytes) / (1024 * 1024), 2) AS size_mb FROM dba_segments WHERE segment_type = 'TABLE' GROUP BY owner, segment_name ORDER BY size_mb DESC FETCH FIRST 10 ROWS ONLY;
SELECT ROLE, AUTHENTICATION_TYPE, COMMON, ORACLE_MAINTAINED FROM DBA_ROLES ORDER BY ROLE;

CREATE USER JEISON_BEDOYA IDENTIFIED BY oracle DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA 10M ON USERS;
GRANT CREATE SESSION TO JEISON_BEDOYA;
GRANT CREATE TABLE TO JEISON_BEDOYA;
CREATE TABLE prueba (id NUMBER, nombre VARCHAR2(50));
GRANT CREATE ANY TABLE TO JEISON_BEDOYA;
CREATE TABLE HR.tabla_prueba (id NUMBER, nombre VARCHAR2(50));

CREATE USER prueba2031 IDENTIFIED BY oracle;
GRANT CREATE SESSION, CREATE TABLE TO prueba2031;
ALTER USER prueba2031 ACCOUNT LOCK;
ALTER USER prueba2031 ACCOUNT UNLOCK;
DROP USER prueba2031 CASCADE;

ALTER USER JEISON_BEDOYA IDENTIFIED BY 0212;
ALTER USER JEISON_BEDOYA DEFAULT TABLESPACE rhumano;
ALTER USER JEISON_BEDOYA QUOTA 5M ON rhumano;
CREATE TABLE tabla_pruebas (id NUMBER, nombre VARCHAR2(50));
GRANT CREATE VIEW TO JEISON_BEDOYA;
REVOKE CREATE VIEW FROM JEISON_BEDOYA;
GRANT CREATE VIEW TO JEISON_BEDOYA;

CREATE ROLE ROL2031;
GRANT CREATE TABLE, ALTER ANY TABLE, DROP ANY TABLE TO ROL2031;
GRANT CREATE VIEW, DROP ANY VIEW TO ROL2031;
GRANT CREATE PROCEDURE, ALTER ANY PROCEDURE, DROP ANY PROCEDURE TO ROL2031;
GRANT CREATE SEQUENCE, ALTER ANY SEQUENCE, DROP ANY SEQUENCE TO ROL2031;
GRANT ROL2031 TO JEISON_BEDOYA;

CREATE INDEX idx_employees_dept ON HR.EMPLOYEES(SALARY);
CREATE SEQUENCE seq_employees START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE employees_demo (id_employee NUMBER PRIMARY KEY, nombre VARCHAR2(50));
INSERT INTO employees_demo (id_employee, nombre) VALUES (seq_employees.NEXTVAL, 'Juan');
INSERT INTO employees_demo (id_employee, nombre) VALUES (seq_employees.NEXTVAL, 'Pablo');

CREATE OR REPLACE PROCEDURE insert_location (
    p_location_id IN LOCATIONS.LOCATION_ID%TYPE,
    p_street_address IN LOCATIONS.STREET_ADDRESS%TYPE,
    p_postal_code IN LOCATIONS.POSTAL_CODE%TYPE,
    p_city IN LOCATIONS.CITY%TYPE,
    p_state_province IN LOCATIONS.STATE_PROVINCE%TYPE,
    p_country_id IN LOCATIONS.COUNTRY_ID%TYPE
) AS
BEGIN
    INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
    VALUES (p_location_id, p_street_address, p_postal_code, p_city, p_state_province, p_country_id);
END;
